"""Idempotent demo catalog seed. Existing learner progress is always preserved."""

from sqlmodel import Session

from .database import create_db_and_tables, engine
from .models import ContentUnit, UserState


def _unit(
    unit_id: str,
    unit_type: str,
    title: str,
    evidence_type: str,
    *,
    difficulty: int = 1,
    prerequisites: list[str] | None = None,
    task_data: dict | None = None,
) -> ContentUnit:
    return ContentUnit(
        id=unit_id,
        type=unit_type,
        title=title,
        evidence_type=evidence_type,
        difficulty=difficulty,
        prerequisites=prerequisites or [],
        task_data=task_data or {},
    )


# Concept snippet shown on each API reel (topic-relevant visual, not stock video).
_API_SNIPPETS = {
    "api_05": "200 OK\n404 Not Found\n500 Server Error",
    "api_06": "GET /items?page=2&limit=20",
    "api_07": "401 Unauthorized\n403 Forbidden",
    "api_08": "if not valid(body):\n    return 422",
    "api_09": "PUT /orders/42\n# safe to retry",
    "api_10": "429 Too Many Requests",
    "api_11": '{ "error": "INVALID_EMAIL" }',
    "api_12": "POST /users\n-> 201 { id }",
    "api_13": "Cache-Control: max-age=60",
    "api_14": "Access-Control-Allow-Origin: *",
    "api_15": "POST /webhooks/payment",
    "api_16": "openapi: 3.1.0\npaths:\n  /users:",
}


def _api_reel(unit_id: str, title: str, description: str, skills: list[str], video_url: str) -> ContentUnit:
    return _unit(
        unit_id,
        "video",
        title,
        "exposure",
        task_data={
            "topic": "apis",
            "skills": skills,
            "goal_tags": ["backend developer", "software engineer"],
            "interest_tags": ["backend", "systems", "apis"],
            "description": description,
            "snippet": _API_SNIPPETS.get(unit_id, "GET /api/resource\n-> 200 OK"),
            "duration_seconds": 25,
            "video_url": video_url,
            "related_learning_unit_id": "api_lesson_01",
        },
    )


API_DISCOVERY_REELS = [
    _api_reel("api_05", "What a status code tells you", "A status code is the server's compact answer: 2xx worked, 4xx points to the request, and 5xx points to a server problem.", ["HTTP", "REST APIs"], "/media/urban-routine.mp4"),
    _api_reel("api_06", "Why APIs paginate big lists", "Pagination breaks a huge response into smaller pages, making an endpoint quicker to load and easier on the server.", ["REST APIs", "Performance"], "/media/city-movement.mp4"),
    _api_reel("api_07", "The useful difference between 401 and 403", "401 means the request has not proved who it is. 403 means the server knows who you are but still denies this action.", ["HTTP", "Authentication"], "/media/workspace-motion.mp4"),
    _api_reel("api_08", "Why an API needs validation", "Validate incoming data at the server boundary so malformed values do not leak into business logic or storage.", ["REST APIs", "Validation"], "/media/nature-detail.mp4"),
    _api_reel("api_09", "When retrying a request is safe", "Idempotent requests can be repeated without applying the same change twice. That matters when a network drops and a client retries.", ["HTTP", "Reliability"], "/media/urban-routine.mp4"),
    _api_reel("api_10", "How rate limits protect an API", "A rate limit caps requests over time, protecting a service from accidental bursts and giving clients a clear retry boundary.", ["REST APIs", "Reliability"], "/media/city-movement.mp4"),
    _api_reel("api_11", "Why APIs return structured errors", "A consistent error body gives a client a stable code and message to act on instead of forcing it to guess from plain text.", ["REST APIs", "HTTP"], "/media/workspace-motion.mp4"),
    _api_reel("api_12", "What an API contract is for", "A contract describes routes, inputs, outputs, and errors so frontend and backend work can evolve without guesswork.", ["REST APIs", "API design"], "/media/nature-detail.mp4"),
    _api_reel("api_13", "Caching can make repeat reads faster", "A cache reuses a recent response when its data is still valid, reducing repeated work for both the client and the service.", ["REST APIs", "Performance"], "/media/urban-routine.mp4"),
    _api_reel("api_14", "Why CORS belongs to the browser boundary", "CORS is a browser-enforced rule that lets a server declare which other origins may read its responses.", ["REST APIs", "Web security"], "/media/city-movement.mp4"),
    _api_reel("api_15", "A webhook sends the update to you", "Polling asks again and again. A webhook lets a service call your endpoint when an event actually happens.", ["REST APIs", "Integrations"], "/media/workspace-motion.mp4"),
    _api_reel("api_16", "How OpenAPI makes endpoints visible", "An OpenAPI description lists an API's operations and schemas so tools can document and inspect the contract automatically.", ["REST APIs", "API design"], "/media/nature-detail.mp4"),
]


UNITS = [
    _unit(
        "api_01",
        "video",
        "Why APIs Matter",
        "exposure",
        task_data={
            "topic": "apis",
            "snippet": "GET /api/products\n-> 200 OK",
            "skills": ["REST APIs"],
            "goal_tags": ["backend developer", "software engineer"],
            "interest_tags": ["backend", "systems", "apis"],
            "description": "An API gives a product a clear, reliable boundary between the interface and its data.",
            "duration_seconds": 30,
            "video_url": "/media/urban-routine.mp4",
            "related_learning_unit_id": "api_lesson_01",
        },
    ),
    _unit(
        "api_lesson_01",
        "lesson",
        "Follow one request through the system",
        "exposure",
        prerequisites=["api_01"],
        task_data={
            "topic": "apis",
            "skills": ["REST APIs"],
            "goal_tags": ["backend developer", "software engineer"],
            "interest_tags": ["backend", "systems", "apis"],
            "duration_seconds": 90,
            "next_path_unit_id": "api_02",
            "lesson_steps": [
                {
                    "eyebrow": "01 — THE ASK",
                    "heading": "A screen asks for one thing.",
                    "body": "When a page needs a list of users, it sends a request that names the resource and the action. GET /users says: read the users collection.",
                    "visual_label": "CLIENT REQUEST",
                    "visual_value": "GET /users",
                },
                {
                    "eyebrow": "02 — THE BOUNDARY",
                    "heading": "The API owns the doorway.",
                    "body": "The browser talks to the API, not straight to the database. The API checks the request, applies the rules, and decides what data can leave the server.",
                    "visual_label": "SERVER ROUTE",
                    "visual_value": "CHECK → ROUTE",
                },
                {
                    "eyebrow": "03 — THE RETURN",
                    "heading": "A useful response comes back.",
                    "body": "The server reads the data it needs and returns a response, often JSON. The screen can then render that response. This boundary keeps the interface and storage loosely coupled.",
                    "visual_label": "RESPONSE",
                    "visual_value": "200 · JSON",
                },
            ],
        },
    ),
    _unit(
        "api_02",
        "quiz",
        "Choose the right HTTP method",
        "concept",
        prerequisites=["api_lesson_01"],
        task_data={
            "topic": "apis",
            "skills": ["HTTP"],
            "goal_tags": ["backend developer", "software engineer"],
            "interest_tags": ["backend", "systems", "apis"],
            "question": "Which HTTP method retrieves a list of users?",
            "options": ["GET", "POST", "PATCH", "DELETE"],
            "answer": "GET",
            "explanation": "GET reads a resource. POST is used to create or submit one.",
            "duration_seconds": 60,
            "next_path_unit_id": "api_03",
        },
    ),
    _unit(
        "api_03",
        "challenge",
        "Fix the API request",
        "application",
        difficulty=2,
        prerequisites=["api_02"],
        task_data={
            "topic": "apis",
            "skills": ["HTTP", "REST APIs"],
            "goal_tags": ["backend developer", "software engineer"],
            "interest_tags": ["backend", "coding", "apis"],
            "interaction": "code_fix",
            "prompt": "This request only needs to read users. Correct its method.",
            "code_before": "fetch('/users', { method: 'POST' })",
            "field_label": "method",
            "options": ["GET", "POST", "PATCH", "DELETE"],
            "answer": "GET",
            "duration_seconds": 120,
            "next_path_unit_id": "api_04",
        },
    ),
    _unit(
        "api_04",
        "challenge",
        "Build GET /users",
        "build",
        difficulty=3,
        prerequisites=["api_03"],
        task_data={
            "topic": "apis",
            "skills": ["REST APIs", "Python"],
            "goal_tags": ["backend developer", "software engineer"],
            "interest_tags": ["backend", "coding", "building"],
            "interaction": "build_endpoint",
            "prompt": "Assemble the smallest useful read endpoint.",
            "starter_method": "GET",
            "starter_path": "/users",
            "collection_name": "users",
            "sample_users": [
                {"id": 1, "name": "Asha Patel", "role": "Backend learner"},
                {"id": 2, "name": "Leo Chen", "role": "API learner"},
            ],
            "steps": [
                "Define a GET route at /users",
                "Read the user collection",
                "Return the collection as JSON",
            ],
            "duration_seconds": 180,
        },
    ),
    *API_DISCOVERY_REELS,
    _unit(
        "sql_01",
        "video",
        "How relational data fits together",
        "exposure",
        task_data={
            "topic": "databases",
            "snippet": "SELECT *\nFROM orders\nJOIN customers USING (id)",
            "skills": ["SQL"],
            "goal_tags": ["backend developer", "data analyst", "software engineer"],
            "interest_tags": ["backend", "databases", "data"],
            "description": "A relational database organizes information into connected tables so an application can ask precise questions.",
            "duration_seconds": 35,
            "video_url": "/media/city-movement.mp4",
            "related_learning_unit_id": "sql_lesson_01",
        },
    ),
    _unit(
        "sql_lesson_01",
        "lesson",
        "Read a result set before you filter it",
        "exposure",
        prerequisites=["sql_01"],
        task_data={
            "topic": "databases",
            "skills": ["SQL"],
            "goal_tags": ["backend developer", "data analyst", "software engineer"],
            "interest_tags": ["backend", "databases", "data"],
            "duration_seconds": 90,
            "next_path_unit_id": "sql_02",
            "lesson_steps": [
                {
                    "eyebrow": "01 — CHOOSE COLUMNS",
                    "heading": "SELECT describes the shape.",
                    "body": "A query starts by naming the columns you want back. SELECT email, name makes a smaller, clearer result than pulling every column by default.",
                    "visual_label": "RESULT SHAPE",
                    "visual_value": "SELECT → COLUMNS",
                },
                {
                    "eyebrow": "02 — CHOOSE A TABLE",
                    "heading": "FROM names the source.",
                    "body": "FROM users tells the database which table supplies those columns. A table is a set of related records, and each row represents one record.",
                    "visual_label": "DATA SOURCE",
                    "visual_value": "FROM users",
                },
                {
                    "eyebrow": "03 — NARROW THE SET",
                    "heading": "WHERE keeps matching rows.",
                    "body": "A WHERE condition removes rows that do not match your rule. SELECT chooses columns; WHERE chooses rows. Together they make a precise question for the database.",
                    "visual_label": "FILTER",
                    "visual_value": "WHERE active = true",
                },
            ],
        },
    ),
    _unit(
        "sql_02",
        "quiz",
        "Filter a query with SQL",
        "concept",
        prerequisites=["sql_lesson_01"],
        task_data={
            "topic": "databases",
            "skills": ["SQL"],
            "goal_tags": ["backend developer", "data analyst", "software engineer"],
            "interest_tags": ["backend", "databases", "data"],
            "question": "Which SQL clause filters rows before they are returned?",
            "options": ["WHERE", "ORDER BY", "SELECT", "JOIN"],
            "answer": "WHERE",
            "explanation": "WHERE applies a condition to rows in the result.",
            "duration_seconds": 60,
            "next_path_unit_id": "sql_03",
        },
    ),
    _unit(
        "sql_03",
        "challenge",
        "Choose the join for customer orders",
        "application",
        difficulty=2,
        prerequisites=["sql_02"],
        task_data={
            "topic": "databases",
            "skills": ["SQL", "Data modeling"],
            "goal_tags": ["backend developer", "data analyst", "software engineer"],
            "interest_tags": ["backend", "databases", "coding"],
            "interaction": "fill_blank",
            "prompt": "Keep every customer, even those with no orders. Tap the join that fits.",
            "template": "SELECT c.name, o.id\nFROM customers c\n___ orders o ON o.customer_id = c.id;",
            "filename": "orders.sql",
            "options": ["LEFT JOIN", "INNER JOIN", "CROSS JOIN"],
            "answer": "LEFT JOIN",
            "explanation": "LEFT JOIN keeps every customer row and matches orders when present.",
            "duration_seconds": 120,
        },
    ),
    _unit(
        "auth_01",
        "video",
        "What OAuth is responsible for",
        "exposure",
        prerequisites=["api_02"],
        task_data={
            "topic": "security",
            "snippet": "Authorization:\n  Bearer <token>",
            "skills": ["Authentication"],
            "goal_tags": ["backend developer", "security engineer", "software engineer"],
            "interest_tags": ["backend", "security", "systems"],
            "description": "OAuth lets one application grant another limited access without sharing the user's password.",
            "duration_seconds": 35,
            "video_url": "/media/workspace-motion.mp4",
            "related_learning_unit_id": "auth_lesson_01",
        },
    ),
    _unit(
        "auth_lesson_01",
        "lesson",
        "Separate identity from permission",
        "exposure",
        prerequisites=["auth_01"],
        task_data={
            "topic": "security",
            "skills": ["Authentication", "Authorization"],
            "goal_tags": ["backend developer", "security engineer", "software engineer"],
            "interest_tags": ["backend", "security", "systems"],
            "duration_seconds": 90,
            "next_path_unit_id": "auth_02",
            "lesson_steps": [
                {
                    "eyebrow": "01 — WHO ARE YOU?",
                    "heading": "Authentication proves identity.",
                    "body": "A login flow checks that a person controls an account. The application then needs a safe way to recognize that person on later requests.",
                    "visual_label": "IDENTITY",
                    "visual_value": "PROVE → SESSION",
                },
                {
                    "eyebrow": "02 — WHAT CAN YOU DO?",
                    "heading": "Authorization checks access.",
                    "body": "Knowing who someone is does not answer what they may do. The server checks a role, ownership rule, or permission before returning protected data.",
                    "visual_label": "PERMISSION",
                    "visual_value": "USER → CAN READ?",
                },
                {
                    "eyebrow": "03 — KEEP THE TOKEN SAFE",
                    "heading": "The browser should not expose secrets.",
                    "body": "Session tokens need careful storage and transport. An HttpOnly cookie cannot be read by page JavaScript, which reduces one route for token theft.",
                    "visual_label": "COOKIE RULE",
                    "visual_value": "HttpOnly · Secure",
                },
            ],
        },
    ),
    _unit(
        "auth_02",
        "quiz",
        "Store a browser session safely",
        "concept",
        difficulty=2,
        prerequisites=["auth_lesson_01"],
        task_data={
            "topic": "security",
            "skills": ["Authentication", "Web security"],
            "goal_tags": ["backend developer", "security engineer", "software engineer"],
            "interest_tags": ["backend", "security", "systems"],
            "question": "Which cookie setting prevents browser JavaScript from reading a session token?",
            "options": ["HttpOnly", "Public", "Readable", "Shared"],
            "answer": "HttpOnly",
            "explanation": "HttpOnly cookies are not available through document.cookie.",
            "duration_seconds": 75,
            "next_path_unit_id": "auth_03",
        },
    ),
    _unit(
        "auth_03",
        "challenge",
        "Order a protected endpoint",
        "application",
        difficulty=3,
        prerequisites=["auth_02"],
        task_data={
            "topic": "security",
            "skills": ["Authentication", "Python"],
            "goal_tags": ["backend developer", "security engineer", "software engineer"],
            "interest_tags": ["backend", "security", "coding"],
            "interaction": "parsons",
            "prompt": "Place the dependency before the protected route handler.",
            "blocks": ["def protected_user(user = Depends(current_user)):", "@app.get('/me')"],
            "solution": ["@app.get('/me')", "def protected_user(user = Depends(current_user)):"],
            "duration_seconds": 150,
        },
    ),
    _unit(
        "docker_01",
        "video",
        "Containers and virtual machines",
        "exposure",
        task_data={
            "topic": "cloud",
            "snippet": "FROM node:20\nCOPY . .\nCMD ['node', 'app.js']",
            "skills": ["Deployment"],
            "goal_tags": ["backend developer", "cloud engineer", "software engineer"],
            "interest_tags": ["backend", "cloud", "systems"],
            "description": "Containers package an application and its dependencies while sharing the host operating-system kernel.",
            "duration_seconds": 35,
            "video_url": "/media/nature-detail.mp4",
            "related_learning_unit_id": "docker_lesson_01",
        },
    ),
    _unit(
        "docker_lesson_01",
        "lesson",
        "Package the app without packing an entire machine",
        "exposure",
        prerequisites=["docker_01"],
        task_data={
            "topic": "cloud",
            "skills": ["Deployment", "Docker"],
            "goal_tags": ["backend developer", "cloud engineer", "software engineer"],
            "interest_tags": ["backend", "cloud", "systems"],
            "duration_seconds": 90,
            "next_path_unit_id": "docker_02",
            "lesson_steps": [
                {
                    "eyebrow": "01 — A SMALLER PACKAGE",
                    "heading": "A container carries the app and its needs.",
                    "body": "A container image groups your application with its runtime and dependencies. That gives the app a repeatable package to run in different environments.",
                    "visual_label": "IMAGE",
                    "visual_value": "APP + DEPENDENCIES",
                },
                {
                    "eyebrow": "02 — SHARE THE HOST",
                    "heading": "Containers share the host kernel.",
                    "body": "A virtual machine includes its own operating system. A container isolates a process while sharing the host kernel, so its footprint is usually smaller.",
                    "visual_label": "RUNTIME",
                    "visual_value": "ISOLATED · SHARED KERNEL",
                },
                {
                    "eyebrow": "03 — DESCRIBE THE RECIPE",
                    "heading": "A Dockerfile makes the package repeatable.",
                    "body": "The Dockerfile names a base image, sets a working directory, copies the source, and defines a command. Order matters because each instruction builds on the layers before it.",
                    "visual_label": "BUILD ORDER",
                    "visual_value": "FROM → COPY → CMD",
                },
            ],
        },
    ),
    _unit(
        "docker_02",
        "challenge",
        "Assemble a small Dockerfile",
        "application",
        difficulty=2,
        prerequisites=["docker_lesson_01"],
        task_data={
            "topic": "cloud",
            "skills": ["Deployment", "Docker"],
            "goal_tags": ["backend developer", "cloud engineer", "software engineer"],
            "interest_tags": ["backend", "cloud", "coding"],
            "interaction": "parsons",
            "prompt": "Order the instructions: choose an image, copy the source, then start the app.",
            "blocks": ["COPY . /app", "CMD ['python', 'main.py']", "FROM python:3.12", "WORKDIR /app"],
            "solution": ["FROM python:3.12", "WORKDIR /app", "COPY . /app", "CMD ['python', 'main.py']"],
            "duration_seconds": 120,
        },
    ),
    _unit(
        "bridge_01",
        "challenge",
        "Connect a React screen to an API",
        "application",
        difficulty=2,
        task_data={
            "topic": "api_integration",
            "skills": ["REST APIs", "JavaScript"],
            "goal_tags": ["backend developer", "software engineer"],
            "interest_tags": ["frontend", "react", "design", "apis", "backend"],
            "relationship": "bridge",
            "interaction": "multiple_choice",
            "prompt": "A React profile screen needs a user's data from the server. Which first step connects the two?",
            "options": ["Fetch GET /users/me", "Read the database file in React", "Hard-code the profile forever"],
            "answer": "Fetch GET /users/me",
            "explanation": "The UI calls a backend endpoint; the backend owns database access.",
            "duration_seconds": 120,
        },
    ),
    _unit("fe_01", "video", "Why the DOM is a tree", "exposure", task_data={"topic": "frontend", "skills": ["DOM", "JavaScript"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "ui", "javascript"], "description": "The browser turns your HTML into a tree of nodes; changing the page means changing that tree.", "snippet": "document.querySelector('.card')", "duration_seconds": 30, "related_learning_unit_id": "fe_lesson_01"}),
    _unit("fe_02", "video", "What the browser does with your CSS", "exposure", task_data={"topic": "frontend", "skills": ["CSS"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "ui", "design"], "description": "CSS rules are matched to elements, then cascaded by specificity. The most specific rule wins.", "snippet": ".btn.primary { color: #fff }", "duration_seconds": 30}),
    _unit("fe_03", "video", "State is just data that changes", "exposure", task_data={"topic": "frontend", "skills": ["React", "State"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "react"], "description": "UI = f(state). When the data changes, the framework recomputes what the screen should show.", "snippet": "const [n, setN] = useState(0)", "duration_seconds": 30}),
    _unit("fe_04", "video", "Why React re-renders", "exposure", task_data={"topic": "frontend", "skills": ["React"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "react"], "description": "Updating state marks a component dirty; React re-runs it and patches only what changed in the DOM.", "snippet": "setState(next) -> re-render", "duration_seconds": 30}),
    _unit("fe_05", "video", "Flexbox in one idea", "exposure", task_data={"topic": "frontend", "skills": ["CSS", "Layout"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "ui", "design"], "description": "A flex container lays children along one axis; justify-content spaces them, align-items aligns them.", "snippet": "display: flex; gap: 12px", "duration_seconds": 30}),
    _unit("fe_lesson_01", "lesson", "Follow one render through React", "exposure", prerequisites=["fe_01"], task_data={"topic": "frontend", "skills": ["React"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "react"], "duration_seconds": 90, "next_path_unit_id": "fe_quiz_01", "lesson_steps": [{"eyebrow": "01 - STATE", "heading": "State holds what can change.", "body": "A component keeps small pieces of state. useState gives you the value and a setter to update it.", "visual_label": "STATE", "visual_value": "useState(0)"}, {"eyebrow": "02 - EVENT", "heading": "An event updates state.", "body": "A click calls the setter. React marks the component as needing to re-render.", "visual_label": "EVENT", "visual_value": "onClick -> setState"}, {"eyebrow": "03 - RENDER", "heading": "React recomputes the view.", "body": "The component runs again with the new state; React diffs the output and updates only what changed.", "visual_label": "RENDER", "visual_value": "diff -> patch"}]}),
    _unit("fe_quiz_01", "quiz", "Choose the React state hook", "concept", prerequisites=["fe_lesson_01"], task_data={"topic": "frontend", "skills": ["React"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "react"], "question": "Which hook stores component state?", "options": ["useState", "useEffect", "useMemo", "useRef"], "answer": "useState", "explanation": "useState returns the value and a setter.", "duration_seconds": 60, "next_path_unit_id": "fe_challenge_01"}),
    _unit("fe_challenge_01", "challenge", "Fix the click handler", "application", difficulty=2, prerequisites=["fe_quiz_01"], task_data={"topic": "frontend", "skills": ["React", "JavaScript"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "react", "coding"], "interaction": "fill_blank", "prompt": "Increment the counter on click. Fill the setter.", "template": "<button onClick={() => ___(count + 1)}>+1</button>", "filename": "Counter.jsx", "options": ["setCount", "count", "useState", "render"], "answer": "setCount", "explanation": "Call the state setter with the next value.", "duration_seconds": 120}),
    _unit("da_01", "video", "What a dataframe is", "exposure", task_data={"topic": "data", "skills": ["Pandas", "Data"], "goal_tags": ["data analyst", "software engineer"], "interest_tags": ["data", "analytics"], "description": "A dataframe is a table in memory: named columns and rows of records, built for fast filtering and grouping.", "snippet": "df = pd.read_csv('sales.csv')", "duration_seconds": 30, "related_learning_unit_id": "da_lesson_01"}),
    _unit("da_02", "video", "Mean vs median, quickly", "exposure", task_data={"topic": "data", "skills": ["Statistics"], "goal_tags": ["data analyst"], "interest_tags": ["data", "analytics", "statistics"], "description": "The mean moves with outliers; the median is the middle value and barely flinches. Skewed data? Use the median.", "snippet": "df['pay'].median()", "duration_seconds": 30}),
    _unit("da_03", "video", "Why you clean data first", "exposure", task_data={"topic": "data", "skills": ["Data cleaning"], "goal_tags": ["data analyst"], "interest_tags": ["data", "analytics"], "description": "Missing values, duplicates and wrong types quietly break every chart downstream. Clean before you conclude.", "snippet": "df.dropna().drop_duplicates()", "duration_seconds": 30}),
    _unit("da_04", "video", "GROUP BY in one picture", "exposure", task_data={"topic": "data", "skills": ["SQL", "Aggregation"], "goal_tags": ["data analyst", "backend developer"], "interest_tags": ["data", "databases"], "description": "GROUP BY buckets rows by a key, then an aggregate (SUM, COUNT, AVG) collapses each bucket to one number.", "snippet": "GROUP BY region -> SUM(sales)", "duration_seconds": 30}),
    _unit("da_lesson_01", "lesson", "Read, then summarise a table", "exposure", prerequisites=["da_01"], task_data={"topic": "data", "skills": ["Pandas"], "goal_tags": ["data analyst"], "interest_tags": ["data", "analytics"], "duration_seconds": 90, "next_path_unit_id": "da_quiz_01", "lesson_steps": [{"eyebrow": "01 - LOAD", "heading": "Load the data.", "body": "read_csv pulls a file into a dataframe. .head() shows the first rows so you can sanity-check columns.", "visual_label": "LOAD", "visual_value": "read_csv -> df"}, {"eyebrow": "02 - FILTER", "heading": "Keep the rows you need.", "body": "A boolean mask selects rows. df[df.active] keeps only active records.", "visual_label": "FILTER", "visual_value": "df[df.active]"}, {"eyebrow": "03 - SUMMARISE", "heading": "Collapse to an answer.", "body": "groupby plus an aggregate turns many rows into a small summary you can chart.", "visual_label": "SUMMARISE", "visual_value": "groupby().sum()"}]}),
    _unit("da_quiz_01", "quiz", "Pick the outlier-resistant measure", "concept", prerequisites=["da_lesson_01"], task_data={"topic": "data", "skills": ["Statistics"], "goal_tags": ["data analyst"], "interest_tags": ["data", "analytics"], "question": "Which measure is least affected by a few extreme values?", "options": ["Median", "Mean", "Sum", "Range"], "answer": "Median", "explanation": "The median is the middle value, so extremes barely move it.", "duration_seconds": 60, "next_path_unit_id": "da_challenge_01"}),
    _unit("da_challenge_01", "challenge", "Complete the aggregation", "application", difficulty=2, prerequisites=["da_quiz_01"], task_data={"topic": "data", "skills": ["SQL", "Aggregation"], "goal_tags": ["data analyst", "backend developer"], "interest_tags": ["data", "databases", "coding"], "interaction": "fill_blank", "prompt": "Total sales per region. Fill the aggregate.", "template": "SELECT region, ___(amount)\nFROM sales\nGROUP BY region;", "filename": "sales.sql", "options": ["SUM", "WHERE", "ORDER BY", "COUNT"], "answer": "SUM", "explanation": "SUM adds the amounts within each region bucket.", "duration_seconds": 120}),
    _unit("cloud_02", "video", "What a load balancer does", "exposure", task_data={"topic": "cloud", "skills": ["Deployment", "Scaling"], "goal_tags": ["cloud engineer", "backend developer"], "interest_tags": ["cloud", "systems"], "description": "A load balancer spreads incoming requests across several servers so no single one is overwhelmed.", "snippet": "client -> LB -> [web-1, web-2]", "duration_seconds": 30}),
    _unit("cloud_03", "video", "Why environment variables", "exposure", task_data={"topic": "cloud", "skills": ["Config", "Deployment"], "goal_tags": ["cloud engineer", "backend developer"], "interest_tags": ["cloud", "systems"], "description": "Secrets and per-environment config live in env vars, not in code, so the same image runs anywhere.", "snippet": "DATABASE_URL=...", "duration_seconds": 30}),
    _unit("cloud_04", "video", "CI/CD in one sentence", "exposure", task_data={"topic": "cloud", "skills": ["CI/CD", "Deployment"], "goal_tags": ["cloud engineer", "software engineer"], "interest_tags": ["cloud", "systems"], "description": "CI builds and tests every change automatically; CD ships the passing build to an environment with no manual steps.", "snippet": "push -> build -> test -> deploy", "duration_seconds": 30}),
    _unit("sec_02", "video", "Why you hash passwords", "exposure", task_data={"topic": "security", "skills": ["Authentication", "Hashing"], "goal_tags": ["security engineer", "backend developer"], "interest_tags": ["security", "systems"], "description": "Store a one-way hash, never the password itself. Even if the database leaks, the real passwords don't.", "snippet": "hash = bcrypt(password)", "duration_seconds": 30}),
    _unit("sec_03", "video", "What HTTPS actually protects", "exposure", task_data={"topic": "security", "skills": ["Web security", "TLS"], "goal_tags": ["security engineer", "backend developer"], "interest_tags": ["security", "systems"], "description": "TLS encrypts data in transit, so someone on the network can't read or tamper with the request.", "snippet": "TLS: encrypt in transit", "duration_seconds": 30}),
    _unit("sec_04", "video", "SQL injection in one line", "exposure", task_data={"topic": "security", "skills": ["Web security", "SQL"], "goal_tags": ["security engineer", "backend developer"], "interest_tags": ["security", "databases"], "description": "Concatenating user input into SQL lets an attacker rewrite your query. Use parameters, always.", "snippet": "WHERE name = ?   -- not + input", "duration_seconds": 30}),
    _unit("fe_fix_01", "challenge", "Fix the click handler", "application", difficulty=2,
        task_data={"topic": "frontend", "skills": ["React", "JavaScript"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "react", "coding"],
        "interaction": "code_fix", "prompt": "This button should update state when clicked. Fix the handler.",
        "code_before": "<button onClick={setCount}>+1</button>", "field_label": "onClick",
        "options": ["() => setCount(count + 1)", "setCount", "count + 1", "setCount(count)"], "answer": "() => setCount(count + 1)",
        "duration_seconds": 120}),
    _unit("fe_parsons_01", "challenge", "Order a React component", "application", difficulty=2,
        task_data={"topic": "frontend", "skills": ["React"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "react", "coding"],
        "interaction": "parsons", "prompt": "Declare the component, then its state, then what it renders.",
        "blocks": ["return <span>{count}</span>;", "const [count] = useState(0);", "function Counter() {"],
        "solution": ["function Counter() {", "const [count] = useState(0);", "return <span>{count}</span>;"],
        "duration_seconds": 150}),
    _unit("da_fill_01", "challenge", "Total revenue per region", "application", difficulty=2,
        task_data={"topic": "data", "skills": ["Pandas"], "goal_tags": ["data analyst", "software engineer"], "interest_tags": ["data", "pandas", "coding"],
        "interaction": "fill_blank", "prompt": "Sum revenue within each region. Tap the aggregation.",
        "template": "df.groupby('region')['revenue'].___()", "filename": "sales.py",
        "options": ["sum", "count", "drop"], "answer": "sum",
        "explanation": "sum() totals revenue within each region group.", "duration_seconds": 120}),
    _unit("da_parsons_01", "challenge", "Order a pandas pipeline", "application", difficulty=2,
        task_data={"topic": "data", "skills": ["Pandas"], "goal_tags": ["data analyst", "software engineer"], "interest_tags": ["data", "pandas", "coding"],
        "interaction": "parsons", "prompt": "Load the data, filter it, then aggregate.",
        "blocks": ["df = df[df.active]", "df = pd.read_csv('users.csv')", "df.groupby('plan').size()"],
        "solution": ["df = pd.read_csv('users.csv')", "df = df[df.active]", "df.groupby('plan').size()"],
        "duration_seconds": 150}),
    _unit("cloud_fix_01", "challenge", "Fix the exposed port", "application", difficulty=2,
        task_data={"topic": "cloud", "skills": ["Docker", "Deployment"], "goal_tags": ["cloud engineer", "backend developer", "software engineer"], "interest_tags": ["cloud", "devops", "coding"],
        "interaction": "code_fix", "prompt": "The app listens on 8080. Expose the matching port.",
        "code_before": "EXPOSE 3000", "field_label": "EXPOSE",
        "options": ["EXPOSE 8080", "EXPOSE 3000", "EXPOSE 22", "EXPOSE 80"], "answer": "EXPOSE 8080",
        "duration_seconds": 120}),
    _unit("sec_fix_01", "challenge", "Fix the password check", "application", difficulty=2,
        task_data={"topic": "security", "skills": ["Authentication", "Python"], "goal_tags": ["security engineer", "backend developer", "software engineer"], "interest_tags": ["security", "backend", "coding"],
        "interaction": "code_fix", "prompt": "Never compare raw passwords. Verify against the stored hash.",
        "code_before": "if password == user.password:", "field_label": "check",
        "options": ["if verify(password, user.hash):", "if password == user.password:", "if password:", "if user.password:"], "answer": "if verify(password, user.hash):",
        "duration_seconds": 120}),
    _unit("api_parsons_01", "challenge", "Order a FastAPI route", "application", difficulty=2,
        task_data={"topic": "apis", "skills": ["REST APIs", "Python"], "goal_tags": ["backend developer", "software engineer"], "interest_tags": ["backend", "apis", "coding"],
        "interaction": "parsons", "prompt": "Decorator first, then the handler, then what it returns.",
        "blocks": ["return {'status': 'ok'}", "@app.get('/health')", "def health():"],
        "solution": ["@app.get('/health')", "def health():", "return {'status': 'ok'}"],
        "duration_seconds": 150}),
    _unit("fe_build_01", "challenge", "Build a Counter UI", "application", difficulty=3,
        task_data={"topic": "frontend", "skills": ["React", "UI"], "goal_tags": ["frontend developer", "software engineer"], "interest_tags": ["frontend", "react", "coding"],
        "interaction": "build_ui", "prompt": "Assemble a reactive UI component.", "duration_seconds": 180}),
]


def seed_db() -> None:
    create_db_and_tables()
    with Session(engine) as session:
        for unit in UNITS:
            session.merge(unit)
        # This former reflection card was removed from the product flow. Its
        # learner events, if any, stay in the append-only event log.
        retired_career_unit = session.get(ContentUnit, "career_01")
        if retired_career_unit is not None:
            session.delete(retired_career_unit)
        if session.get(UserState, "u1") is None:
            session.add(UserState(user_id="u1", declared_goal="Backend Developer"))
        session.commit()


if __name__ == "__main__":
    seed_db()
    print(f"Seeded {len(UNITS)} content units without deleting learner progress.")
